name: Build

on:
  workflow_call:
    inputs:
      package-version:
        type: string
        required: false
        default: 1.0-SNAPSHOT
        description: Output CodeGame package version

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build & Test
        run: mvn --batch-mode --update-snapshots --activate-profiles unit,component test

      - name: Checkstyle
        run: mvn --batch-mode checkstyle:checkstyle

      - name: Get Version
        id: get-version
        run: |
          VERSION=${{ inputs.package-version }} 
          VERSION=${VERSION/#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Package
        run: mvn --batch-mode package -DskipTests -Drevision=${{ steps.get-version.outputs.version }}

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          path: target/CodeGame-*-fat.jar
          retention-days: 7

      - name: Javadoc
        run: mvn --batch-mode javadoc:javadoc -Drevision=${{ steps.get-version.outputs.version }}

      - name: Upload Javadoc
        uses: actions/upload-pages-artifact@v2
        with:
          name: javadoc
          path: target/site/apidocs
          retention-days: 7

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Integration Test
        run: mvn --batch-mode --activate-profiles integration,headless test
