name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      enable-sonarqube-scan: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
