name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  app:
    name: CodeGame Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build & Test
        run: mvn --batch-mode --update-snapshots --activate-profiles unit,component,coverage test

      - name: Checkstyle
        run: mvn --batch-mode checkstyle:checkstyle

      - name: Integration Test
        run: mvn --batch-mode --activate-profiles integration,headless test

      - name: Package
        run: mvn --batch-mode --activate-profiles coverage package -DskipTests

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          path: target/CodeGame-*-fat.jar
          retention-days: 3

      - name: Javadoc
        run: mvn --batch-mode javadoc:javadoc

      - name: Upload Javadoc
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: target/site/apidocs/*
          retention-days: 3

      - name: SonarQube Scan
        run: mvn --batch-mode -DskipTests -Dsonar.projectKey=CodeGame sonar:sonar
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
