name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  app:
    name: CodeGame Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Build & Test
        run: mvn --batch-mode --update-snapshots test

      - name: Package
        run: mvn --batch-mode package

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          path: target/CodeGame-*-fat.jar
          retention-days: 3
